### PR TITLE
Multitarget .NET Core and mono

### PR DESCRIPTION
**Pull request by Suchiman**
`netstandard` is more targeted at library authors that want to run on both platforms. Referencing `mscorlib` from `netstandard` isn't a particularly good idea, it's an implementation assembly of .NET Framework, although it is available as a typeforwarder in .NET Core. The common approach is to multitarget the project, which will build once for each target but that requires that the target framework is appended to the output path. This builds successfully without warnings.

Ref #68

### CODE REVIEW

**Comment by Krinkle** [comment]
@Suchiman Thanks, I didn't realise `netcoreapp` was supported by Mono as well. Is that right?

Would netcoreapp3.0 work here as well? I looks like netcoreapp3.1 might be too new.

**Comment by Suchiman** [comment]
@Krinkle not yet AFAIK, mono will support `net5.0` (which is the next version after .NET Core 3.1 which drops the "core" suffix again but is distinct from the net472 line of frameworks).

This modification just creates an `net472` output folder on build which will run on mono like it used to and an `netcoreapp3.1` folder that will run on .NET Core.

Yes, netcoreapp3.0 would work as well, but just as an heads up: .NET Core 3.0 was a "current" release, it is EOL as of `March 3, 2020`, .NET Core 3.1 is an LTS release.

**Comment by Suchiman** [comment]
That seems to have passed and produced 4 outputs:
```
  CVNBot -> /home/travis/build/countervandalism/CVNBot/src/CVNBot/bin/Release/net472/CVNBot.exe
  CVNBot -> /home/travis/build/countervandalism/CVNBot/src/CVNBot/bin/Release/netcoreapp3.1/CVNBot.dll

  CVNBot -> /home/travis/build/countervandalism/CVNBot/src/CVNBot/bin/Debug/net472/CVNBot.exe
  CVNBot -> /home/travis/build/countervandalism/CVNBot/src/CVNBot/bin/Debug/netcoreapp3.1/CVNBot.dll
```
the `net472\CVNBot.exe` assembly should be runnable with mono and `netcoreapp3.1/CVNBot.dll` with `dotnet`.

**Comment by Krinkle** [comment]
@Suchiman I see, I don't mind that it's EOL though, it's weird, I know, but it just isn't a factor for this service. Once we're past this stage, we can certainly upgrade though, but would prefer to take it one step at a time.

Would you expect it to work on both Mono and dotnet if we use netcoreapp3.0? See https://github.com/countervandalism/CVNBot/commit/db7dbfd3f7237d28ee12b877230c68efcf237af2 for the Travis CI template.

**Comment by Suchiman** [comment]
Do you want me to downgrade to 3.0, given that the build for 3.1 works?
With my travis tweaks, it builds the mono and dotnet version using the dotnet tooling alone.

Running the netcoreapp output using the mono runtime is at present not supported, it did work for an hello world but failed with `System.TypeLoadException: Could not resolve type with token 01000017` when trying CVNBot.

The netcoreapp version will also need further tweaks to get log4net up and running at runtime, it needs `<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />` in order to be able to load the legacy .exe.config file format and then some tweaks to how the config loaded.

**Comment by Krinkle** [comment]
@Suchiman  I was hoping the project could build and run with Mono and its msbuild (Linux/macOS), and build and run cross-platform with dotnet as well.... and we all live happily ever after!  😁

Does that seems feasible or is this a strange question? I'm not sure myself.

* The CI runs so far show that targets `netcoreapp3.1;net472` would build fine with dotnet 3.1 on Linux, but fail with Mono.
* For me locally, I find that targets `netcoreapp3.0;net472` builds fine with Mono msbuild on macOS. ~~But fails when I use dotnet build, since NET Framework 4.7.2 is missing. I assume this is because NET Framework is primarily a legacy Windows framework only partially ported cross platform and only within Mono, is that right? Or is there a way to build and run net472 with dotnet outside Windows?~~

It seems a game of whack-a-mole so maybe that's a sign I'm trying something unsupported.

**Comment by Suchiman** [comment]
I see what you want, not requiring a dependency on the .NET Core tooling.
I haven't kept track much of what has been happening on the mono side of things regarding "SDK msbuild" support. I know that as part of .NET 5 or .NET 6, mono will be available as a runtime inside the `dotnet` tooling, at which point you can basically say "dotnet run --using-runtime=mono". It would suprise me if you could build a netcoreapp with the mono tooling (given that mono cannot run that yet), but theoretically it could work if mono had the reference assemblies for that.

I've also just noticed that it's using SmartIrc4Net, that won't work on .NET Core, primarily due to using `Thread.Abort` (a dangerous API that has been discontinued in .NET Core / throws `PlatformNotSupportedException`). I've forked that library for personal projects sometime ago and tweaked it to make it work on .NET Core: https://github.com/Suchiman/Irc4netButSmarter

**Comment by Krinkle** [comment]
Closing in favour of https://github.com/countervandalism/CVNBot/issues/73.

**Pull request closed without merging**
